
default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1

  pool: 5
  socket: /var/run/mysqld/mysqld.sock


staging:
  <<: *default
  database: debtgeo_staging
  username: common
  password: password

development:
  <<: *default
  database: debtgeo_development
  username: debtgeo_dev
  password: sad43297DF29

production:
  <<: *default
  database: debtgeo_production
  username: debtgeo_prod
  password: dg23iosd78
